import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import SideBar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark overflow-hidden bg-background text-foreground min-h-screen flex w-full`}>
        <SideBar />
        <div className="w-full px-4 md:px-8 max-h-screen overflow-auto">
          <Header />
          <div className="pt-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
